language: node_js
node_js:
  - node
install:
  - npm ci
script:
  - npm run build:dist
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
